a=input('Enter first number: ')
b=input('Enter second number: ')
sum=float(a)+float(b)
subtract=float(a)-float(b)
product=float(a)*float(b)
divide=float(a)/float(b)
remainder=float(a)%float(b)
print('sum of {0} and {1} is: {2}'. format(a,b,sum))
print('subtract of {0} and {1} is: {2}'. format(a,b,subtract))
print('product of {0} and {1} is: {2}'. format(a,b,product))
print('divide of {0} and {1} is: {2}'. format(a,b,divide))
print('remainder of {0} and {1} is: {2}'. format(a,b,remainder))